from __future__ import annotations

import argparse
from pathlib import Path

import polars as pl
import pyarrow as pa

import ynab_il_importer.review_app.io as review_io
from ynab_il_importer.artifacts.review_schema import REVIEW_SCHEMA


def _record(
    *,
    review_transaction_id: str,
    workflow_type: str,
    relation_kind: str,
    match_status: str,
    match_method: str,
    payee_options: str,
    category_options: str,
    decision_action: str,
    reviewed: bool,
    source_present: bool,
    target_present: bool,
    source_row_id: str,
    target_row_id: str,
    source_account: str,
    target_account: str,
    source_date: str,
    target_date: str,
    source_memo: str,
    target_memo: str,
    source_fingerprint: str,
    target_fingerprint: str,
    source_payee_selected: str,
    source_category_selected: str,
    target_payee_selected: str,
    target_category_selected: str,
    source_current: dict[str, object] | None,
    target_current: dict[str, object] | None,
    source_original: dict[str, object] | None = None,
    target_original: dict[str, object] | None = None,
    source_context_kind: str = "",
    source_context_category_id: str = "",
    source_context_category_name: str = "",
    source_context_matching_split_ids: str = "",
    target_context_kind: str = "",
    target_context_matching_split_ids: str = "",
    memo_append: str = "",
    update_maps: str = "",
) -> dict[str, object]:
    return {
        "artifact_kind": "review_artifact",
        "artifact_version": "review_v4",
        "review_transaction_id": review_transaction_id,
        "workflow_type": workflow_type,
        "relation_kind": relation_kind,
        "match_status": match_status,
        "match_method": match_method,
        "payee_options": payee_options,
        "category_options": category_options,
        "update_maps": update_maps,
        "decision_action": decision_action,
        "reviewed": reviewed,
        "changed": False,
        "memo_append": memo_append,
        "source_present": source_present,
        "target_present": target_present,
        "source_row_id": source_row_id,
        "target_row_id": target_row_id,
        "target_account": target_account,
        "source_context_kind": source_context_kind,
        "source_context_category_id": source_context_category_id,
        "source_context_category_name": source_context_category_name,
        "source_context_matching_split_ids": source_context_matching_split_ids,
        "source_payee_selected": source_payee_selected,
        "source_category_selected": source_category_selected,
        "target_context_kind": target_context_kind,
        "target_context_matching_split_ids": target_context_matching_split_ids,
        "target_payee_selected": target_payee_selected,
        "target_category_selected": target_category_selected,
        "source_current": source_current,
        "target_current": target_current,
        "source_original": source_original or source_current,
        "target_original": target_original or target_current,
    }


def _txn(
    *,
    source_system: str,
    transaction_id: str,
    account_name: str,
    date: str,
    payee_raw: str,
    category_raw: str,
    memo: str,
    inflow_ils: float,
    outflow_ils: float,
    fingerprint: str,
    matched_transaction_id: str = "",
    ynab_id: str = "",
    account_id: str = "",
    import_id: str = "",
    approved: bool = False,
    cleared: str = "",
    splits: list[dict[str, object]] | None = None,
) -> dict[str, object]:
    return {
        "artifact_kind": "demo_transaction",
        "artifact_version": "transaction_v1",
        "source_system": source_system,
        "transaction_id": transaction_id,
        "ynab_id": ynab_id,
        "import_id": import_id,
        "parent_transaction_id": transaction_id,
        "account_id": account_id,
        "account_name": account_name,
        "source_account": account_name,
        "date": date,
        "secondary_date": "",
        "inflow_ils": inflow_ils,
        "outflow_ils": outflow_ils,
        "signed_amount_ils": inflow_ils - outflow_ils,
        "payee_raw": payee_raw,
        "category_id": "",
        "category_raw": category_raw,
        "memo": memo,
        "txn_kind": "",
        "fingerprint": fingerprint,
        "description_raw": memo,
        "description_clean": memo,
        "description_clean_norm": "",
        "merchant_raw": payee_raw,
        "ref": "",
        "matched_transaction_id": matched_transaction_id,
        "cleared": cleared,
        "approved": approved,
        "is_subtransaction": False,
        "splits": splits,
    }


def _split(
    *,
    split_id: str,
    parent_transaction_id: str,
    payee_raw: str,
    category_raw: str,
    memo: str,
    inflow_ils: float,
    outflow_ils: float,
) -> dict[str, object]:
    return {
        "split_id": split_id,
        "parent_transaction_id": parent_transaction_id,
        "ynab_subtransaction_id": split_id,
        "payee_raw": payee_raw,
        "category_id": "",
        "category_raw": category_raw,
        "memo": memo,
        "inflow_ils": inflow_ils,
        "outflow_ils": outflow_ils,
        "import_id": "",
        "matched_transaction_id": "",
    }


def demo_review_records() -> list[dict[str, object]]:
    bank_regular = _txn(
        source_system="bank",
        transaction_id="bank-regular-1",
        account_name="Family Leumi",
        date="2026-03-01",
        payee_raw="Cafe Roma",
        category_raw="",
        memo="morning coffee",
        inflow_ils=0.0,
        outflow_ils=22.0,
        fingerprint="cafe roma",
    )
    ynab_regular = _txn(
        source_system="ynab",
        transaction_id="ynab-regular-1",
        ynab_id="ynab-regular-1",
        account_name="Family Leumi",
        account_id="acct-family",
        date="2026-03-01",
        payee_raw="Cafe Roma",
        category_raw="Going out",
        memo="morning coffee",
        inflow_ils=0.0,
        outflow_ils=22.0,
        fingerprint="cafe roma",
        approved=True,
        cleared="cleared",
    )
    split_parent = _txn(
        source_system="ynab",
        transaction_id="ynab-split-1",
        ynab_id="ynab-split-1",
        account_name="Shared Budget",
        account_id="acct-shared",
        date="2026-03-02",
        payee_raw="Bookstore Combo",
        category_raw="Split",
        memo="books and gifts",
        inflow_ils=0.0,
        outflow_ils=140.0,
        fingerprint="bookstore combo",
        approved=True,
        cleared="uncleared",
        splits=[
            _split(
                split_id="split-book-1",
                parent_transaction_id="ynab-split-1",
                payee_raw="Bookstore Combo",
                category_raw="Books",
                memo="novel",
                inflow_ils=0.0,
                outflow_ils=90.0,
            ),
            _split(
                split_id="split-gift-1",
                parent_transaction_id="ynab-split-1",
                payee_raw="Bookstore Combo",
                category_raw="Gifts",
                memo="birthday card",
                inflow_ils=0.0,
                outflow_ils=50.0,
            ),
        ],
    )
    target_split = _txn(
        source_system="ynab",
        transaction_id="ynab-target-split-1",
        ynab_id="ynab-target-split-1",
        account_name="Family Leumi",
        account_id="acct-family",
        date="2026-03-03",
        payee_raw="Mega Store",
        category_raw="Split",
        memo="house and groceries",
        inflow_ils=0.0,
        outflow_ils=180.0,
        fingerprint="mega store",
        approved=False,
        cleared="uncleared",
        splits=[
            _split(
                split_id="split-house-1",
                parent_transaction_id="ynab-target-split-1",
                payee_raw="Mega Store",
                category_raw="House and stuff",
                memo="cleaning supplies",
                inflow_ils=0.0,
                outflow_ils=120.0,
            ),
            _split(
                split_id="split-food-1",
                parent_transaction_id="ynab-target-split-1",
                payee_raw="Mega Store",
                category_raw="Groceries",
                memo="snacks",
                inflow_ils=0.0,
                outflow_ils=60.0,
            ),
        ],
    )
    bank_target_split_source = _txn(
        source_system="bank",
        transaction_id="bank-target-split-1",
        account_name="Family Leumi",
        date="2026-03-03",
        payee_raw="Mega Store",
        category_raw="",
        memo="house and groceries",
        inflow_ils=0.0,
        outflow_ils=180.0,
        fingerprint="mega store",
    )
    transfer_source = _txn(
        source_system="bank",
        transaction_id="bank-transfer-1",
        account_name="Family Leumi",
        date="2026-03-04",
        payee_raw="Transfer bank leumi",
        category_raw="",
        memo="credit card payment",
        inflow_ils=0.0,
        outflow_ils=950.0,
        fingerprint="transfer bank leumi",
    )

    return [
        _record(
            review_transaction_id="demo-regular",
            workflow_type="institutional",
            relation_kind="source_target_pair",
            match_status="matched_auto",
            match_method="exact_amount_date",
            payee_options="Cafe Roma",
            category_options="Going out",
            decision_action="keep_match",
            reviewed=False,
            source_present=True,
            target_present=True,
            source_row_id="bank-regular-1",
            target_row_id="ynab-regular-1",
            source_account="Family Leumi",
            target_account="Family Leumi",
            source_date="2026-03-01",
            target_date="2026-03-01",
            source_memo="morning coffee",
            target_memo="morning coffee",
            source_fingerprint="cafe roma",
            target_fingerprint="cafe roma",
            source_payee_selected="",
            source_category_selected="",
            target_payee_selected="Cafe Roma",
            target_category_selected="Going out",
            source_current=bank_regular,
            target_current=ynab_regular,
        ),
        _record(
            review_transaction_id="demo-source-split-context",
            workflow_type="cross_budget",
            relation_kind="source_target_pair",
            match_status="ambiguous",
            match_method="category_extract",
            payee_options="Bookstore Combo",
            category_options="Books;Gifts",
            decision_action="No decision",
            reviewed=False,
            source_present=True,
            target_present=False,
            source_row_id="ynab-split-1",
            target_row_id="",
            source_account="Shared Budget",
            target_account="Family Leumi",
            source_date="2026-03-02",
            target_date="",
            source_memo="books and gifts",
            target_memo="",
            source_fingerprint="bookstore combo",
            target_fingerprint="",
            source_payee_selected="Bookstore Combo",
            source_category_selected="Books",
            target_payee_selected="Bookstore Combo",
            target_category_selected="Books",
            source_current=split_parent,
            target_current=None,
            source_context_kind="ynab_split_category_match",
            source_context_category_id="cat-books",
            source_context_category_name="Books",
            source_context_matching_split_ids="split-book-1",
        ),
        _record(
            review_transaction_id="demo-target-split",
            workflow_type="institutional",
            relation_kind="source_target_pair",
            match_status="matched_auto",
            match_method="fingerprint_map",
            payee_options="Mega Store",
            category_options="House and stuff;Groceries",
            decision_action="keep_match",
            reviewed=False,
            source_present=True,
            target_present=True,
            source_row_id="bank-target-split-1",
            target_row_id="ynab-target-split-1",
            source_account="Family Leumi",
            target_account="Family Leumi",
            source_date="2026-03-03",
            target_date="2026-03-03",
            source_memo="house and groceries",
            target_memo="house and groceries",
            source_fingerprint="mega store",
            target_fingerprint="mega store",
            source_payee_selected="",
            source_category_selected="",
            target_payee_selected="Mega Store",
            target_category_selected="House and stuff",
            source_current=bank_target_split_source,
            target_current=target_split,
        ),
        _record(
            review_transaction_id="demo-transfer",
            workflow_type="institutional",
            relation_kind="source_only",
            match_status="source_only",
            match_method="fingerprint_map",
            payee_options="Transfer : Opher x9922",
            category_options="None",
            decision_action="create_target",
            reviewed=False,
            source_present=True,
            target_present=False,
            source_row_id="bank-transfer-1",
            target_row_id="",
            source_account="Family Leumi",
            target_account="Family Leumi",
            source_date="2026-03-04",
            target_date="",
            source_memo="credit card payment",
            target_memo="",
            source_fingerprint="transfer bank leumi",
            target_fingerprint="",
            source_payee_selected="",
            source_category_selected="",
            target_payee_selected="Transfer : Opher x9922",
            target_category_selected="None",
            source_current=transfer_source,
            target_current=None,
        ),
    ]


def build_demo(output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    proposed_path = output_dir / "review_app_demo_proposed.parquet"
    categories_path = output_dir / "review_app_demo_categories.csv"
    table = pa.Table.from_pylist(demo_review_records(), schema=REVIEW_SCHEMA)
    review_io.save_review_artifact(table, proposed_path)
    categories = pl.DataFrame(
        {
            "category_group": [
                "Living",
                "Living",
                "Living",
                "Living",
                "Internal Master Category",
            ],
            "category_name": [
                "Going out",
                "Books",
                "Gifts",
                "House and stuff",
                "Uncategorized",
            ],
        }
    )
    categories.write_csv(categories_path, include_bom=True)
    return proposed_path, categories_path


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build a canonical demo review artifact.")
    parser.add_argument(
        "--out-dir",
        default="data/demo/review_app",
        help="Directory where the demo parquet and categories CSV should be written.",
    )
    return parser


def main() -> None:
    args = _build_arg_parser().parse_args()
    proposed_path, categories_path = build_demo(Path(args.out_dir))
    print(f"Wrote demo review artifact to {proposed_path}")
    print(f"Wrote demo categories to {categories_path}")


if __name__ == "__main__":
    main()
